/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.cip.view;

import es.cip.bussines.bl.JFCambioTipoUsuarioBL;
import es.cip.bussines.dao.model.RecursoHumanoDatos;
import es.cip.bussines.dao.model.TipoUsuario;
import es.cip.util.Cte;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author iMac
 */
public class JFCambioTipoUsuario extends javax.swing.JFrame {

    private final DefaultTableModel modelTabla;
    private final JFCambioTipoUsuarioBL bl;
    private boolean van;

    /**
     * Creates new form JFCambioTipoUsuario
     */
    public JFCambioTipoUsuario() {
        bl = new JFCambioTipoUsuarioBL();
        initComponents();

        modelTabla = (DefaultTableModel) jTableUsuario.getModel();
        modelTabla.setNumRows(0);

        TableColumn col = jTableUsuario.getColumnModel().getColumn(5);

        //String op[] = {"Masculino", "Femenino"};
        //jComboBox1 = new JComboBox(op);
        for (TipoUsuario obj : bl.listTipoUsuario()) {
            jComboBox1.addItem(obj.getTipo());
        }
        col.setCellEditor(new DefaultCellEditor(jComboBox1));
        modelTabla.setNumRows(0);
        for (RecursoHumanoDatos recursoHumanoDatos : bl.findNombreCompleto("")) {
            modelTabla.addRow(new Object[]{recursoHumanoDatos.getUsuario().getNombre() + " " + recursoHumanoDatos.getUsuario().getApellidoPaterno() + " " + recursoHumanoDatos.getUsuario().getApellidoMaterno(),
                recursoHumanoDatos.getUniversidad().getNombre(),
                recursoHumanoDatos.getCampus().getNombre(),
                recursoHumanoDatos.getCarrera().getNombreCarrera(),
                recursoHumanoDatos.getUsuario().getCorreoElectronico(),
                recursoHumanoDatos.getTipoUsuario().getTipo()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableUsuario = new javax.swing.JTable();
        txtTutor = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Universidad", "Campus", "Carrera", "Correo", "Tipo Usuario"
            }
        ));
        jScrollPane4.setViewportView(jTableUsuario);

        txtTutor.setText("Usuario");

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyReleased(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("* Para cambiar de clic en la columna Tipo Usuario y seleccione uno nuevo ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(txtTutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 779, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTutor))
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyReleased
        // TODO add your handling code here:
        modelTabla.setNumRows(0);
        for (RecursoHumanoDatos recursoHumanoDatos : bl.findNombreCompleto(jTextFieldNombre.getText().trim())) {
            modelTabla.addRow(new Object[]{recursoHumanoDatos.getUsuario().getNombre() + " " + recursoHumanoDatos.getUsuario().getApellidoPaterno() + " " + recursoHumanoDatos.getUsuario().getApellidoMaterno(),
                recursoHumanoDatos.getUniversidad().getNombre(),
                recursoHumanoDatos.getCampus().getNombre(),
                recursoHumanoDatos.getCarrera().getNombreCarrera(),
                recursoHumanoDatos.getUsuario().getCorreoElectronico(),
                recursoHumanoDatos.getTipoUsuario().getTipo()
            });
        }
    }//GEN-LAST:event_jTextFieldNombreKeyReleased

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
//        if (jTableUsuario.getSelectedRow() >= 0) {
//            System.out.println(jTableUsuario.getValueAt(jTableUsuario.getSelectedRow(), 5) + "- jComboBox1ItemStateChanged -" + jComboBox1.getItemAt(jComboBox1.getSelectedIndex()));
//        }
        van=true;
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if (jTableUsuario.getSelectedRow() >= 0 && van) {
            try {
                //System.out.println("\n\n"+jTableUsuario.getValueAt(jTableUsuario.getSelectedRow(), 5) + "- jComboBox1ActionPerformed -" + jComboBox1.getItemAt(jComboBox1.getSelectedIndex()));
                bl.guardar(jTableUsuario.getSelectedRow(), jComboBox1.getSelectedIndex());
                
                van=false;
            } catch (Exception ex) {
                Logger.getLogger(JFCambioTipoUsuario.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,Cte.Error_BD+"\n"+ ex);
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFCambioTipoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFCambioTipoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFCambioTipoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFCambioTipoUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFCambioTipoUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableUsuario;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JLabel txtTutor;
    // End of variables declaration//GEN-END:variables
}
