/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.cip.view;

import es.cip.bussines.bl.JFRegistroPersonaBL;
import es.cip.util.Cte;
import es.cip.util.ValidCampos;
import java.awt.Cursor;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Vero
 */
public class JFRegistroPersona extends javax.swing.JFrame {

    private JFDatosAcademicos datosAcademicos;
    private boolean valCampos = true;
    private JFRegistroPersonaBL bL = new JFRegistroPersonaBL();

    /**  Datos Personales
     * Creates new form JFRegistroPersona
     */
    public JFRegistroPersona() {
        this.setTitle(Cte.Titulo_JFRegistroPersona);
        initComponents();

        jLabelNombre.setVisible(false);
        jLabelApePaterno.setVisible(false);
        jLabelApeMaterno.setVisible(false);
        jLabelUsuar.setVisible(false);
        jLabelPass.setVisible(false);
        jLabelPass1.setVisible(false);
        jLabelTel.setVisible(false);
        jLabelCorreo.setVisible(false);
        jLabelDirec.setVisible(false);
        jLabelColonia.setVisible(false);
        jLabelMunicipio.setVisible(false);
        jLabelNumInt.setVisible(false);
        jLabelNumExt.setVisible(false);

        jLabelNombre.setToolTipText(Cte.Solo_Letras);
        jLabelApePaterno.setToolTipText(Cte.Solo_Letras);
        jLabelApeMaterno.setToolTipText(Cte.Solo_Letras);
        jLabelUsuar.setToolTipText(Cte.Usua_Rep);
        jLabelPass.setToolTipText(Cte.Pass);
        jLabelPass1.setToolTipText(Cte.Pass_Diferente);
        jLabelTel.setToolTipText(Cte.Tel_Erroneo);
        jLabelCorreo.setToolTipText(Cte.Correo_Erroneo);
        jLabelDirec.setToolTipText(Cte.Campo_Vacio);
        jLabelColonia.setToolTipText(Cte.Campo_Vacio);
        jLabelMunicipio.setToolTipText(Cte.Campo_Vacio);
        jLabelNumInt.setToolTipText(Cte.Solo_Numero_Direccion);
        jLabelNumExt.setToolTipText(Cte.Solo_Numero_Direccion);

        jTextFieldNombre.setToolTipText(Cte.Solo_Letras);
        jTextFieldApePaterno.setToolTipText(Cte.Solo_Letras);
        jTextFieldApeMaterno.setToolTipText(Cte.Solo_Letras);
        jTextFieldUsuar.setToolTipText(Cte.Solo_Letras);
        jTextFieldPass.setToolTipText(Cte.Pass);
        jTextFieldPass1.setToolTipText(Cte.Pass_Diferente);
        jTextFieldTelefono.setToolTipText(Cte.Tel_Erroneo);
        jTextFieldCorreo.setToolTipText(Cte.Correo_Erroneo);
        jTextFieldDireccion.setToolTipText(Cte.Campo_Vacio);
        jTextFieldColonia.setToolTipText(Cte.Campo_Vacio);
        jTextFieldMunicipio.setToolTipText(Cte.Campo_Vacio);
        jTextFieldNumInt.setToolTipText(Cte.Solo_Numero);
        jTextFieldNumExt.setToolTipText(Cte.Solo_Numero);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        jTextFieldCorreo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldColonia = new javax.swing.JTextField();
        jTextFieldMunicipio = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldNumExt = new javax.swing.JTextField();
        jTextFieldNumInt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldApePaterno = new javax.swing.JTextField();
        jTextFieldUsuar = new javax.swing.JTextField();
        jTextFieldApeMaterno = new javax.swing.JTextField();
        jButtonAgregar1 = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApePaterno = new javax.swing.JLabel();
        jLabelApeMaterno = new javax.swing.JLabel();
        jLabelUsuar = new javax.swing.JLabel();
        jLabelPass = new javax.swing.JLabel();
        jLabelPass1 = new javax.swing.JLabel();
        jLabelTel = new javax.swing.JLabel();
        jLabelCorreo = new javax.swing.JLabel();
        jLabelDirec = new javax.swing.JLabel();
        jLabelColonia = new javax.swing.JLabel();
        jLabelMunicipio = new javax.swing.JLabel();
        jLabelNumInt = new javax.swing.JLabel();
        jLabelNumExt = new javax.swing.JLabel();
        jTextFieldPass = new javax.swing.JPasswordField();
        jTextFieldPass1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage((new ImageIcon(this.getClass().getResource("/Imagenes/cip.png"))).getImage());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setText("Repetir Contraseña");

        jLabel2.setText("Contraseña");

        jLabel1.setText("Nombre");

        jLabel4.setText("Telefono");

        jLabel5.setText("Correo Electronico ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Datos Personales");

        jTextFieldNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNombreFocusLost(evt);
            }
        });
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyReleased(evt);
            }
        });

        jTextFieldTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldTelefonoFocusLost(evt);
            }
        });
        jTextFieldTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefonoActionPerformed(evt);
            }
        });

        jTextFieldCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCorreoFocusLost(evt);
            }
        });
        jTextFieldCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCorreoActionPerformed(evt);
            }
        });

        jLabel8.setText("Dirección ");

        jTextFieldDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDireccionFocusLost(evt);
            }
        });

        jLabel9.setText("Colonia");

        jTextFieldColonia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldColoniaFocusLost(evt);
            }
        });

        jTextFieldMunicipio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldMunicipioFocusLost(evt);
            }
        });

        jLabel10.setText("Municipio");

        jLabel11.setText("NumInt");

        jLabel12.setText("NumExt");

        jTextFieldNumExt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNumExtFocusLost(evt);
            }
        });

        jTextFieldNumInt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNumIntFocusLost(evt);
            }
        });

        jLabel7.setText("Apellido Paterno");

        jLabel13.setText("Apellido Materno");

        jLabel14.setText("Usuario");

        jTextFieldApePaterno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldApePaternoFocusLost(evt);
            }
        });
        jTextFieldApePaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApePaternoActionPerformed(evt);
            }
        });
        jTextFieldApePaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldApePaternoKeyReleased(evt);
            }
        });

        jTextFieldUsuar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldUsuarFocusLost(evt);
            }
        });
        jTextFieldUsuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarActionPerformed(evt);
            }
        });

        jTextFieldApeMaterno.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldApeMaternoFocusLost(evt);
            }
        });
        jTextFieldApeMaterno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApeMaternoActionPerformed(evt);
            }
        });
        jTextFieldApeMaterno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldApeMaternoKeyReleased(evt);
            }
        });

        jButtonAgregar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar.png"))); // NOI18N
        jButtonAgregar1.setText("Agregar");
        jButtonAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregar1ActionPerformed(evt);
            }
        });

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(204, 0, 0));
        jLabelNombre.setText("*");

        jLabelApePaterno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelApePaterno.setForeground(new java.awt.Color(204, 0, 0));
        jLabelApePaterno.setText("*");

        jLabelApeMaterno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelApeMaterno.setForeground(new java.awt.Color(204, 0, 0));
        jLabelApeMaterno.setText("*");

        jLabelUsuar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelUsuar.setForeground(new java.awt.Color(204, 0, 0));
        jLabelUsuar.setText("*");

        jLabelPass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPass.setForeground(new java.awt.Color(204, 0, 0));
        jLabelPass.setText("*");

        jLabelPass1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPass1.setForeground(new java.awt.Color(204, 0, 0));
        jLabelPass1.setText("*");

        jLabelTel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTel.setForeground(new java.awt.Color(204, 0, 0));
        jLabelTel.setText("*");

        jLabelCorreo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelCorreo.setForeground(new java.awt.Color(204, 0, 0));
        jLabelCorreo.setText("*");

        jLabelDirec.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDirec.setForeground(new java.awt.Color(204, 0, 0));
        jLabelDirec.setText("*");

        jLabelColonia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelColonia.setForeground(new java.awt.Color(204, 0, 0));
        jLabelColonia.setText("*");

        jLabelMunicipio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelMunicipio.setForeground(new java.awt.Color(204, 0, 0));
        jLabelMunicipio.setText("*");

        jLabelNumInt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNumInt.setForeground(new java.awt.Color(204, 0, 0));
        jLabelNumInt.setText("*");

        jLabelNumExt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNumExt.setForeground(new java.awt.Color(204, 0, 0));
        jLabelNumExt.setText("*");

        jTextFieldPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPassFocusLost(evt);
            }
        });

        jTextFieldPass1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPass1FocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNumInt, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addComponent(jTextFieldMunicipio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldColonia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldNumExt)
                    .addComponent(jTextFieldApePaterno)
                    .addComponent(jTextFieldUsuar)
                    .addComponent(jTextFieldApeMaterno)
                    .addComponent(jButtonAgregar1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldPass)
                    .addComponent(jTextFieldPass1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabelNombre)
                                                    .addComponent(jLabelApePaterno, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addComponent(jLabelApeMaterno, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addComponent(jLabelUsuar)
                                            .addComponent(jLabelPass, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(jLabelPass1, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabelTel)
                                    .addComponent(jLabelCorreo)
                                    .addComponent(jLabelDirec, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jLabelColonia, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabelMunicipio, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(jLabelNumInt, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabelNumExt))
                .addContainerGap())
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldApePaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelApePaterno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextFieldApeMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelApeMaterno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextFieldUsuar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUsuar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabelPass)
                            .addComponent(jTextFieldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabelPass1)
                            .addComponent(jTextFieldPass1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCorreo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDirec))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelColonia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldMunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMunicipio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextFieldNumInt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabelNumInt)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldNumExt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumExt))
                .addGap(22, 22, 22)
                .addComponent(jButtonAgregar1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCorreoActionPerformed

    private void jTextFieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldApePaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApePaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApePaternoActionPerformed

    private void jTextFieldUsuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarActionPerformed

    private void jTextFieldApeMaternoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApeMaternoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApeMaternoActionPerformed

    private void jButtonAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregar1ActionPerformed

        valCampos = true;
        valCampos = !ValidCampos.esSoloLetras(jTextFieldNombre.getText().trim()) ? false : valCampos;
        valCampos = !ValidCampos.esSoloLetras(jTextFieldApePaterno.getText().trim()) ? false : valCampos;
        valCampos = !ValidCampos.esSoloLetras(jTextFieldApeMaterno.getText().trim()) ? false : valCampos;
        //valCampos = !ValidCampos.esSoloLetras(jTextFieldUsuar.getText().trim()) ? false : valCampos;
        valCampos = !bL.extNickname(jTextFieldUsuar.getText().trim()) ? false : valCampos;
        valCampos = !ValidCampos.esPassVal(jTextFieldPass.getText().trim()) ? false : valCampos;
        valCampos = !jTextFieldPass.getText().trim().equalsIgnoreCase(jTextFieldPass1.getText().trim()) ? false : valCampos;
        valCampos = !ValidCampos.esTelefono(jTextFieldTelefono.getText().trim()) ? false : valCampos;
        valCampos = !ValidCampos.validarEmail(jTextFieldCorreo.getText().trim()) ? false : valCampos;
        valCampos = jTextFieldDireccion.getText().trim() == "" ? false : valCampos;
        valCampos = jTextFieldColonia.getText().trim() == "" ? false : valCampos;
        valCampos = jTextFieldMunicipio.getText().trim() == "" ? false : valCampos;
        valCampos = !ValidCampos.esNumeroCasa(jTextFieldNumInt.getText().trim()) ? false : valCampos;
        valCampos = !ValidCampos.esNumeroCasa(jTextFieldNumExt.getText().trim()) ? false : valCampos;

        if (valCampos || CampNull()) {

            try {
                bL.getUsuario().setNombre(jTextFieldNombre.getText().trim());
                bL.getUsuario().setApellidoPaterno(jTextFieldApePaterno.getText().trim());
                bL.getUsuario().setApellidoMaterno(jTextFieldApeMaterno.getText().trim());
                bL.getUsuario().setTelefono(jTextFieldTelefono.getText().trim());
                bL.getUsuario().setCorreoElectronico(jTextFieldCorreo.getText().trim());
                bL.getUsuario().setCalle(jTextFieldDireccion.getText().trim());
                bL.getUsuario().setColonia(jTextFieldColonia.getText().trim());
                bL.getUsuario().setMunicipio(jTextFieldMunicipio.getText().trim());
                bL.getUsuario().setNumInt(jTextFieldNumInt.getText().trim());
                bL.getUsuario().setNumExt(jTextFieldNumExt.getText().trim());
                bL.getUsuario().setNickname(jTextFieldUsuar.getText().trim());
                bL.getLogin().setPassword(jTextFieldPass.getText());
                bL.guardar();
                
                datosAcademicos = new JFDatosAcademicos();
                datosAcademicos.setNickname(jTextFieldUsuar.getText().trim());
                datosAcademicos.setVisible(true);
                this.setVisible(!datosAcademicos.isVisible());
            } catch (Exception ex) {
                Logger.getLogger(JFRegistroPersona.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, ex);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, Cte.Falta_llenar_Campos);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgregar1ActionPerformed

    private void jTextFieldNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreFocusLost
        // TODO add your handling code here:
        jLabelNombre.setVisible(!ValidCampos.esSoloLetras(jTextFieldNombre.getText().trim()));
    }//GEN-LAST:event_jTextFieldNombreFocusLost

    private void jTextFieldApePaternoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldApePaternoFocusLost
        // TODO add your handling code here:
        jLabelApePaterno.setVisible(!ValidCampos.esSoloLetras(jTextFieldApePaterno.getText().trim()));
    }//GEN-LAST:event_jTextFieldApePaternoFocusLost

    private void jTextFieldApeMaternoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldApeMaternoFocusLost
        // TODO add your handling code here:
        jLabelApeMaterno.setVisible(!ValidCampos.esSoloLetras(jTextFieldApeMaterno.getText().trim()));
    }//GEN-LAST:event_jTextFieldApeMaternoFocusLost

    private void jTextFieldUsuarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldUsuarFocusLost
        // TODO add your handling code here:
        //jLabelUsuar.setVisible(!ValidCampos.sonLetrasNumeroSinEspacios(jTextFieldUsuar.getText().trim()));
        jLabelUsuar.setVisible(!bL.extNickname(jTextFieldUsuar.getText().trim()));
//        if (!ValidCampos.esSoloLetras(jTextFieldUsuar.getText().trim()) || !bL.extNickname(jTextFieldUsuar.getText().trim())) {
//            jLabelUsuar.setVisible(true);
//        } else {
//            jLabelUsuar.setVisible(false);
//        }
    }//GEN-LAST:event_jTextFieldUsuarFocusLost

    private void jTextFieldTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoFocusLost
        // TODO add your handling code here:
        jLabelTel.setVisible(!ValidCampos.esTelefono(jTextFieldTelefono.getText().trim()));
    }//GEN-LAST:event_jTextFieldTelefonoFocusLost

    private void jTextFieldCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCorreoFocusLost
        // TODO add your handling code here:
        jLabelCorreo.setVisible(!ValidCampos.validarEmail(jTextFieldCorreo.getText().trim()));
    }//GEN-LAST:event_jTextFieldCorreoFocusLost

    private void jTextFieldDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDireccionFocusLost
        // TODO add your handling code here:
        jLabelCorreo.setVisible(jTextFieldDireccion.getText().trim() == "");
    }//GEN-LAST:event_jTextFieldDireccionFocusLost

    private void jTextFieldColoniaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldColoniaFocusLost
        // TODO add your handling code here:
        jLabelColonia.setVisible(jTextFieldColonia.getText().trim() == "");
    }//GEN-LAST:event_jTextFieldColoniaFocusLost

    private void jTextFieldMunicipioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldMunicipioFocusLost
        // TODO add your handling code here:
        jLabelMunicipio.setVisible(jTextFieldMunicipio.getText().trim() == "");
    }//GEN-LAST:event_jTextFieldMunicipioFocusLost

    private void jTextFieldNumIntFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNumIntFocusLost
        // TODO add your handling code here:
        jLabelNumInt.setVisible(!ValidCampos.esNumeroCasa(jTextFieldNumInt.getText().trim().toUpperCase()));
    }//GEN-LAST:event_jTextFieldNumIntFocusLost

    private void jTextFieldNumExtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNumExtFocusLost
        // TODO add your handling code here:
        jLabelNumExt.setVisible(!ValidCampos.esNumeroCasa(jTextFieldNumExt.getText().trim().toUpperCase()));
    }//GEN-LAST:event_jTextFieldNumExtFocusLost

    private void jTextFieldPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPassFocusLost
        // TODO add your handling code here:
        jLabelPass.setVisible(!ValidCampos.esPassVal(jTextFieldPass.getText().trim()));
    }//GEN-LAST:event_jTextFieldPassFocusLost

    private void jTextFieldPass1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPass1FocusLost
        // TODO add your handling code here:
        jLabelPass1.setVisible(!jTextFieldPass.getText().trim().equalsIgnoreCase(jTextFieldPass1.getText().trim()));
    }//GEN-LAST:event_jTextFieldPass1FocusLost

    private void jTextFieldNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyReleased
        // TODO add your handling code here:
        jTextFieldNombre.setText(jTextFieldNombre.getText().toUpperCase());
    }//GEN-LAST:event_jTextFieldNombreKeyReleased

    private void jTextFieldApePaternoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApePaternoKeyReleased
        // TODO add your handling code here:
        jTextFieldApePaterno.setText(jTextFieldApePaterno.getText().toUpperCase());
    }//GEN-LAST:event_jTextFieldApePaternoKeyReleased

    private void jTextFieldApeMaternoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApeMaternoKeyReleased
        // TODO add your handling code here:        
        jTextFieldApeMaterno.setText(jTextFieldApeMaterno.getText().toUpperCase());
    }//GEN-LAST:event_jTextFieldApeMaternoKeyReleased
    private boolean CampNull() {
        if (jTextFieldNombre.getText() == ""
                || jTextFieldApePaterno.getText() == ""
                || jTextFieldApeMaterno.getText() == ""
                || jTextFieldUsuar.getText() == ""
                || jTextFieldPass.getText() == ""
                || jTextFieldPass1.getText() == ""
                || jTextFieldTelefono.getText() == ""
                || jTextFieldCorreo.getText() == ""
                || jTextFieldDireccion.getText() == ""
                || jTextFieldColonia.getText() == ""
                || jTextFieldMunicipio.getText() == ""
                || jTextFieldNumInt.getText() == ""
                || jTextFieldNumExt.getText() == "") {
            return true;
        } else {
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRegistroPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRegistroPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRegistroPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRegistroPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFRegistroPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelApeMaterno;
    private javax.swing.JLabel jLabelApePaterno;
    private javax.swing.JLabel jLabelColonia;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelDirec;
    private javax.swing.JLabel jLabelMunicipio;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumExt;
    private javax.swing.JLabel jLabelNumInt;
    private javax.swing.JLabel jLabelPass;
    private javax.swing.JLabel jLabelPass1;
    private javax.swing.JLabel jLabelTel;
    private javax.swing.JLabel jLabelUsuar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldApeMaterno;
    private javax.swing.JTextField jTextFieldApePaterno;
    private javax.swing.JTextField jTextFieldColonia;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldMunicipio;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumExt;
    private javax.swing.JTextField jTextFieldNumInt;
    private javax.swing.JPasswordField jTextFieldPass;
    private javax.swing.JPasswordField jTextFieldPass1;
    private javax.swing.JTextField jTextFieldTelefono;
    private javax.swing.JTextField jTextFieldUsuar;
    // End of variables declaration//GEN-END:variables

//    private void cerrar() {
//        Object [] opciones ={"Aceptar","Cancelar"};
//int eleccion = JOptionPane.showOptionDialog(rootPane,"En realidad desea realizar cerrar la aplicacion","Mensaje de Confirmacion",
//JOptionPane.YES_NO_OPTION,
//JOptionPane.QUESTION_MESSAGE,null,opciones,"Aceptar");
//if (eleccion == JOptionPane.YES_OPTION)
//{
//System.exit(0);
//}else{
//}
//    }
}
