/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.cip.view;

import es.cip.util.cte.Cte;
import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.FlowLayout;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author Vero
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private RegistroPersona registroPersona;
    private RegistroProyecto registroProyecto;
    private AvancesProyecto avancesProyecto;
    private EstadoProyecto estadoProyecto;
    private SeccionPublica SeccionPublica;
    private Login login;

    /**
     * Creates new form JMenuPrincipal
     */
    public MenuPrincipal() {
        jTabbedPane1 = new JTabbedPane();
        initComponents();
        getContentPane().add(jTabbedPane1, BorderLayout.CENTER);
        this.setLayout(new FlowLayout());
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setAlwaysOnTop(true);

        jButtonCerrar.setContentAreaFilled(false);
        int size = 20;
        jButtonCerrar.setPreferredSize(new Dimension(size, size));
        jButtonCerrar.setToolTipText("Cerrar Pestaña");

        //tabButton.setText("...");
        jButtonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/boton_cerrar.gif")));
        try {
            login = new Login();
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            SeccionPublica = new SeccionPublica();
            pestana(SeccionPublica, Cte.Seccion_Publica);
            this.pack();
            this.setExtendedState(MAXIMIZED_BOTH);
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCerrar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuIniciarSesion = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuRegUsua = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemCrearProy = new javax.swing.JMenuItem();
        jMenuItemModProy = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        jButtonCerrar.setText("jButton1");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setToolTipText("");
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jMenu1.setText("Archivo");

        jMenuIniciarSesion.setText("Iniciar sesión ");
        jMenuIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuIniciarSesionActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuIniciarSesion);

        jMenuItem2.setText("Cerrar sesión ");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuRegUsua.setText("Registro de Usuario ");
        jMenuRegUsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRegUsuaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuRegUsua);

        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Proyecto ");

        jMenuItemCrearProy.setText("Crear Proyecto");
        jMenuItemCrearProy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCrearProyActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemCrearProy);

        jMenuItemModProy.setText("Actualizar proyectos ");
        jMenuItemModProy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemModProyActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemModProy);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Administrador ");

        jMenuItem1.setText("Aprobar Proyectos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ayuda");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1061, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        // TODO add your handling code here:
        if (jTabbedPane1.getSelectedIndex() >= 0) {
            String temp = jTabbedPane1.getTitleAt(jTabbedPane1.getSelectedIndex());

            jTabbedPane1.removeTabAt(jTabbedPane1.getSelectedIndex());
        }
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jMenuIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuIniciarSesionActionPerformed
        try {
            // TODO add your handling code here:
            
            login.setVisible(true);
            login.setAlwaysOnTop(true);
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuIniciarSesionActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.removeAll();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuRegUsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRegUsuaActionPerformed
        // TODO add your handling code here:
        try {
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            registroPersona = new RegistroPersona();
            //this.add(pantallaHerramentero, BorderLayout.CENTER);
            pestana(registroPersona, Cte.Alta_Usuario);
            this.pack();
            this.setExtendedState(MAXIMIZED_BOTH);
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        }
    }//GEN-LAST:event_jMenuRegUsuaActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jMenuItemCrearProyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCrearProyActionPerformed
        // TODO add your handling code here:
        try {
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            registroProyecto = new RegistroProyecto();
            pestana(registroProyecto, Cte.Registro_Proyecto);
            this.pack();
            this.setExtendedState(MAXIMIZED_BOTH);
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        }
    }//GEN-LAST:event_jMenuItemCrearProyActionPerformed

    private void jMenuItemModProyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemModProyActionPerformed
        // TODO add your handling code here:
        try {
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            avancesProyecto = new AvancesProyecto();
            pestana(avancesProyecto, Cte.Avances_Proyecto);
            this.pack();
            this.setExtendedState(MAXIMIZED_BOTH);
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        }
    }//GEN-LAST:event_jMenuItemModProyActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        try {
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            estadoProyecto = new EstadoProyecto();
            pestana(estadoProyecto, Cte.Estado_Proyecto);
            this.pack();
            this.setExtendedState(MAXIMIZED_BOTH);
            this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
        } catch (Exception ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        System.out.println(jTabbedPane1.getSelectedIndex());
        if (jTabbedPane1.getSelectedIndex() > -1) {
            JPanel pnl = new JPanel();
            pnl.setOpaque(false);
            JLabel label = new JLabel(jTabbedPane1.getTitleAt(jTabbedPane1.getSelectedIndex()));
            pnl.add(label);
            pnl.add(jButtonCerrar);
            if (jTabbedPane1.getSelectedIndex() >= 0) {
                jTabbedPane1.setTabComponentAt(jTabbedPane1.getSelectedIndex(), pnl);
            }
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged
    public void pestana(JPanel pantalla, String title) {

        jTabbedPane1.addTab(title, null, pantalla);
//jTabbedPane1.;
        JPanel pnl = new JPanel();
        pnl.setOpaque(true);
        JLabel label = new JLabel(title);
        pnl.add(label);
        pnl.add(jButtonCerrar);
        jTabbedPane1.setTabComponentAt(jTabbedPane1.getTabCount() - 1, pnl);
        jTabbedPane1.setSelectedIndex(jTabbedPane1.getTabCount() - 1);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuIniciarSesion;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemCrearProy;
    private javax.swing.JMenuItem jMenuItemModProy;
    private javax.swing.JMenuItem jMenuRegUsua;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
